import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers/react-query-provider";
import ShoppingCart from "@/components/ShoppingCart/ShoppingCart";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className="bg-slate-700">
          <>
            <div className="relative">
              <ShoppingCart />
            </div>
            <div className="flex min-h-screen flex-col  p-24">{children}</div>
          </>
        </body>
      </Providers>
    </html>
  );
}
